apiVersion: apps/v1
kind: Deployment
metadata:
  name: logout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logout
  template:
    metadata:
      labels:
        app: logout
    spec:
      containers:
      - name: logout
        image: 702551696126.dkr.ecr.eu-central-1.amazonaws.com/tms-logout-img:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: logout-service
spec:
  selector:
    app: logout
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
