version: '3.1'

services:

  php:
    build: .
    container_name: php-container
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_DATABASE=task_manager
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      db: 
        condition: service_healthy

  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: task_manager
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -h 'localhost' -u 'root' -p'password' -e 'SELECT 1'",
        ]
      timeout: 20s
      retries: 10
      interval: 10s
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:

volumes:
  db_data:
