apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-tables
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: YOUR_AWS_ID.dkr.ecr.REGION.amazonaws.com/tms-mysql-job-img:latest
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: rds-endpoint
                key: endpoint
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: rds-username
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: rds-password
                key: password
          - name: DB_DATABASE
            value: task_manager
      restartPolicy: Never
  backoffLimit: 4