pipeline {
    agent any

    environment {
        // Define environment variables
        REPOSITORY_URI = '702551696126.dkr.ecr.eu-central-1.amazonaws.com/tms-frontend-img'
        IMAGE_TAG = 'latest'
        AWS_REGION = 'eu-central-1'
        DOCKERFILE_DIR = 'task-management-system/frontend.Dockerfile'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "ls -la ${DOCKERFILE_DIR}"
                    docker.build("$REPOSITORY_URI:$IMAGE_TAG", "$DOCKERFILE_DIR")
                }
            }
        }

        stage('Push Docker Image to ECR') {
            steps {
                script {
                    docker.withRegistry("https://$REPOSITORY_URI", "ecr:eu-central-1:aws-credentials") {
                        docker.image("$REPOSITORY_URI:$IMAGE_TAG").push()
                    }
                }
            }
        }
    }
}
